### ISSUE TITLE
Home screen should be more responsive

### ISSUE THREAD

**Issue by nackermann** [mreinfurt/MusicScheduler#17]
- [x] Pause/Resume should not display the info screen anymore
- [x] Improve the booking

Book a song: Cursor is in the "Youtube URL" field -> press tab -> Cursor is in the "Username" field -> write a name and press enter -> Youtube link disappears and song is booked -> Cursor jumps back to the "Youtube URL" field.

The Enter key tries to book and the tab key switches between both input fields.

**Comment by mreinfurt** [comment]
Can't reproduce "Pause/Resume should not display the info screen anymore", try rebuilding. Booking has been improved.
