### ISSUE TITLE
"Skip" and"Pause/Resume" should be somewhere else

### ISSUE THREAD

**Issue by TheJDP** [mreinfurt/MusicScheduler#4]

**Comment by nackermann** [comment]
@mreinfurt 

Also an alert dialog would be nice for skip

**Comment by mreinfurt** [comment]
I've moved the "Play", "Pause" and "Skip" functionality into the "Currently Playing" view. The play button will toggle the icon. Skip will still directly skip right now. I'll add a popover at the bottom so you have to press twice.

This is how it looks right now: 

<p align="center">
  <img src="http://i.imgur.com/b0l6J6N.png">
</p>
